import streamlit as st
from streamlit_gsheets import GSheetsConnection
import pandas as pd
import datetime
import io
import os
from geopy.geocoders import ArcGIS
from geopy.extra.rate_limiter import RateLimiter

# --- NEW: PDF GENERATION ---
from fpdf import FPDF
import tempfile

# --- CLOUD STORAGE IMPORTS ---
from google.cloud import storage
from google.oauth2 import service_account

# --- SETUP ---
st.set_page_config(page_title="Verify - Cloud MVP", layout="wide")
geolocator = ArcGIS(user_agent="verify_mvp_app")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
conn = st.connection("gsheets", type=GSheetsConnection)

# --- HELPER: PDF GENERATOR ---
def generate_pdf(job):
    # Create the PDF object
    pdf = FPDF()
    pdf.add_page()
    
    # 1. Header
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, "VERIFY | Field Report", ln=True, align='C')
    pdf.ln(10)
    
    # 2. Job Details Table
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(40, 10, "Job ID:", border=0)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, str(job['id']), ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(40, 10, "Address:", border=0)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, job['address'], ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(40, 10, "Date Verified:", border=0)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, str(job['timestamp']), ln=True)
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(40, 10, "GPS Location:", border=0)
    pdf.set_font("Arial", '', 12)
    
    # LOGIC FIX: Check for Null Island
    lat = job['lat']
    lon = job['lon']
    
    if lat == 0.0 and lon == 0.0:
        pdf.set_text_color(255, 0, 0) # Red Text
        pdf.cell(0, 10, "Geocoding Unavailable (Address Verified Manually)", ln=True)
        pdf.set_text_color(0, 0, 0) # Reset to Black
    else:
        pdf.cell(0, 10, f"{lat}, {lon}", ln=True)
    
    pdf.ln(10)
    
    # 3. The Evidence Photo
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Visual Evidence", ln=True)
    pdf.ln(5)
    
    # We need to handle the image carefully. FPDF cannot load images directly from a URL reliably 
    # without downloading them first. For this MVP, we will link to it.
    
    evidence_path = str(job['evidence'])
    if "http" in evidence_path:
        pdf.set_font("Arial", 'I', 10)
        pdf.set_text_color(0, 0, 255)
        pdf.cell(0, 10, "Click Here to View High-Res Evidence in Cloud", ln=True, link=evidence_path)
        
        # NOTE: To embed the actual image, we would need to download it to a temp file first.
        # Keeping it as a link is safer for the MVP to avoid download errors.
        
    pdf.ln(10)
    
    # 4. Chain of Custody Footer
    pdf.set_y(-30)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(128)
    pdf.cell(0, 10, f"Generated by Verify Platform. Cryptographic Hash: SHA-256-SIMULATED", ln=True, align='C')
    pdf.cell(0, 10, f"Timestamp Authority: NTP Stratum-1", ln=True, align='C')
    
    # Return PDF as bytes
    return pdf.output(dest='S').encode('latin-1')

# --- HELPER: GOOGLE BUCKET UPLOADER ---
def upload_to_bucket(file_obj, filename):
    creds_dict = dict(st.secrets["connections"]["gsheets"])
    creds = service_account.Credentials.from_service_account_info(creds_dict)
    client = storage.Client(credentials=creds, project=creds_dict["project_id"])
    bucket = client.bucket("verify-mvp-evidence") # CHECK YOUR BUCKET NAME
    blob = bucket.blob(filename)
    file_obj.seek(0)
    blob.upload_from_file(file_obj, content_type="image/jpeg")
    return blob.public_url

# --- DATA FUNCTIONS ---
def get_data():
    df = conn.read(worksheet="jobs", ttl=0)
    df['lat'] = pd.to_numeric(df['lat'], errors='coerce')
    df['lon'] = pd.to_numeric(df['lon'], errors='coerce')
    df['id'] = pd.to_numeric(df['id']).fillna(0).astype(int)
    return df

def update_job_status(job_id, evidence_file):
    df = get_data()
    clean_id = int(job_id)
    try:
        filename = f"job_{clean_id}_evidence.jpg"
        image_url = upload_to_bucket(evidence_file, filename)
        job_index = df[df['id'] == clean_id].index
        if not job_index.empty:
            idx = job_index[0]
            df.at[idx, 'status'] = 'Complete'
            df.at[idx, 'evidence'] = image_url 
            df.at[idx, 'timestamp'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            conn.update(worksheet="jobs", data=df)
            st.cache_data.clear()
            return True
    except Exception as e:
        st.error(f"STAY ON SCREEN - Upload Failed: {e}")
        return False

import time # Add this to your imports at the top

def add_new_job(address, job_type, bounty, instructions):
    real_lat = 0.0
    real_lon = 0.0
    address_found = False
    
    # 1. Try to Convert Address using ArcGIS
    try:
        # ArcGIS is very robust, usually finds it on the first try
        location = geolocator.geocode(address, timeout=10)
        
        if location:
            real_lat = location.latitude
            real_lon = location.longitude
            address = location.address # Use the clean, official string
            address_found = True
    except Exception as e:
        print(f"Map Error: {e}")
        # If it fails, we fall through to the save block below
        # but address_found remains False.
    
    # 2. Save the Job
    # We save it regardless, but we track if we found the coords
    df = get_data()
    new_id = df['id'].max() + 1 if not df.empty else 101
    
    new_row = pd.DataFrame([{
        "id": int(new_id),
        "address": address, # Saves user input if map failed, or clean address if found
        "lat": real_lat,
        "lon": real_lon,
        "type": job_type,
        "bounty": bounty,
        "status": "Open",
        "instructions": instructions,
        "evidence": "",
        "timestamp": ""
    }])
    
    updated_df = pd.concat([df, new_row], ignore_index=True)
    conn.update(worksheet="jobs", data=updated_df)
    st.cache_data.clear()
    
    return address_found
    
# --- APP INTERFACE ---
st.sidebar.header("🔐 User Simulator")
user_role = st.sidebar.radio("Who are you?", ["Client (Insurance Co)", "Field Agent (Verifier)"])
df = get_data()

if user_role == "Client (Insurance Co)":
    st.title("Verify | Client Portal (Cloud)")
    col1, col2 = st.columns([1, 2])
    
    with col1:
        st.subheader("📍 Dispatch New Job")
        with st.form("new_job_form"):
            addr = st.text_input("Property Address")
            j_type = st.selectbox("Job Type", ["Storm Damage Check", "Occupancy Verification"])
            instr = st.text_area("Instructions")
            price = st.number_input("Bounty Offer ($)", min_value=15, value=35, step=5)
            if st.form_submit_button("🚀 Dispatch"):
                if addr:
                    with st.spinner("Triangulating Coordinates..."):
                        found = add_new_job(addr, j_type, price, instr)
                        
                        if found:
                            st.success("Job Dispatched! Address Verified.")
                        else:
                            st.warning("Job Dispatched, but Map Service could not verify address. (Saved with manual address).")
                        
                        time.sleep(1) # Give user time to read the message
                        st.rerun()
                else:
                    st.warning("Please enter an address.")

    with col2:
        st.subheader("🗺️ Live Operations Map")
        
        # 1. Filter out bad data (Null Island)
        map_df = df[(df['lat'] != 0) & (df['lon'] != 0)].copy()
        
        # 2. Assign Colors based on Status
        # Format is [Red, Green, Blue, Alpha(Transparency)]
        def get_color(status):
            if status == 'Open':
                return [255, 0, 0, 200]  # 🔴 Red for Action Needed
            elif status == 'Complete':
                return [0, 200, 0, 200]  # 🟢 Green for Done
            return [128, 128, 128, 200]  # Gray for unknowns
            
        # Apply the color logic to a new column
        map_df['color'] = map_df['status'].apply(get_color)
        
        # 3. Render Map with Color Column
        st.caption("🔴 Red = Open Requests | 🟢 Green = Completed Jobs")
        st.map(map_df, color="color")
        st.divider()
        st.subheader("📂 Completed Reports")
        completed_jobs = df[df['status'] == 'Complete']
        if completed_jobs.empty:
            st.info("No reports ready yet.")
        else:
            for index, job in completed_jobs.iterrows():
                with st.expander(f"✅ Report #{job['id']} - {job['address']}"):
                    c1, c2 = st.columns(2)
                    with c1:
                        evidence_path = str(job['evidence'])
                        if "http" in evidence_path:
                            st.image(evidence_path, caption="Verified Evidence", width="stretch")
                        elif evidence_path and evidence_path != "nan":
                             st.warning("Legacy file.")
                    with c2:
                        st.write(f"**Verified At:** {job['timestamp']}")
                        st.write(f"**Target Location:** {job['lat']}, {job['lon']}")
                        st.success("✅ CHAIN OF CUSTODY: VERIFIED")
                        
                        # --- NEW: DOWNLOAD BUTTON ---
                        # We generate the PDF bytes on the fly
                        pdf_bytes = generate_pdf(job)
                        
                        st.download_button(
                            label="📄 Download Official PDF Report",
                            data=pdf_bytes,
                            file_name=f"Verify_Report_{job['id']}.pdf",
                            mime="application/pdf"
                        )

else:
    st.title("Verify | Field Agent App")
    open_jobs = df[df['status'] == 'Open']
    if open_jobs.empty:
        st.warning("No gigs available.")
    else:
        for index, job in open_jobs.iterrows():
            with st.container(border=True):
                c1, c2 = st.columns([3, 1])
                with c1:
                    st.write(f"**{job['type']}**")
                    st.caption(f"📍 {job['address']}")
                with c2:
                    if st.button("📸 START", key=f"start_{job['id']}"):
                        st.session_state['active_job'] = int(job['id'])

    if 'active_job' in st.session_state:
        st.divider()
        st.write(f"Active Job ID: {st.session_state['active_job']}")
        picture = st.camera_input("Take Proof")
        if picture:
            if st.button("Submit Evidence"):
                with st.spinner("Uploading to Cloud Bucket..."):
                    success = update_job_status(st.session_state['active_job'], picture)
                    if success:
                        del st.session_state['active_job']
                        st.success("Uploaded! Check Client Dashboard.")
                        st.rerun()
